import { useEffect, useRef, useState } from "react"
import { motion as Motion } from "framer-motion"

export const POLICIES = {
  terms: {
    title: "Terms & Conditions",
    companyName: "JuriNex",
    subtitle: "Nexintel AI Private Limited",
    docTitle: "TERMS AND CONDITIONS OF USE",
    lastUpdated: "Latest Version",
    sections: [
      {
        heading: "1. INTRODUCTION AND ACCEPTANCE",
        paragraphs: [
          `These Terms and Conditions ("Terms") constitute a legally binding agreement between the user ("User", "you") and Nexintel AI Private Limited's product JuriNex ("JuriNex", "we", "us").`,
          `These Terms govern access to and use of the JuriNex platform, website, applications, dashboards, APIs, and related services (collectively, the "Platform").`,
        ],
        important: `BY ACCESSING, REGISTERING ON, OR USING THE PLATFORM IN ANY MANNER, YOU EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO BE LEGALLY BOUND BY THESE TERMS, THE PRIVACY POLICY, AND ALL POLICIES INCORPORATED BY REFERENCE.`,
      },
      {
        heading: "2. NATURE OF PLATFORM AND SERVICES",
        paragraphs: [
          `JuriNex is an artificial intelligence-enabled legal intelligence and research platform intended solely to assist users with information retrieval, structuring of legal content, summaries, drafting assistance, and analytical insights based exclusively on user-provided inputs.`,
          `JuriNex does not provide legal advice, legal opinions, legal representation, strategic counsel, or assurance of any legal, judicial, regulatory, or commercial outcome.`,
          `JuriNex is not a law firm and does not create any advocate-client, attorney-client, fiduciary, advisory, or confidential relationship between the User and JuriNex under any circumstances.`,
        ],
        important: `THE PLATFORM IS A TECHNOLOGY TOOL ONLY.`,
      },
      {
        heading: "3. NO LEGAL ADVICE AND NON-RELIANCE DISCLAIMER",
        paragraphs: [
          `All outputs, analyses, summaries, drafts, responses, or materials generated by the Platform are provided strictly for informational, academic, and internal research purposes only.`,
          `Nothing generated by JuriNex shall be construed as legal advice, legal opinion, or a substitute for consultation with a qualified advocate or legal professional.`,
          `Users expressly acknowledge and agree that they shall not rely upon any output of the Platform for filing, pleading, argument, compliance, decision-making, or representation in any judicial, quasi-judicial, regulatory, or administrative proceeding without independent professional verification.`,
          `Any reliance placed on Platform outputs is entirely at the user's sole risk, and JuriNex expressly disclaims all responsibility arising from such reliance.`,
        ],
      },
      {
        heading: "4. JURISDICTIONAL SCOPE AND GLOBAL ACCESS",
        paragraphs: [
          `The Platform is owned, controlled, and operated from India.`,
          `Users may access the Platform from jurisdictions outside India; however, all matters relating to access to, use of, and interaction with the Platform, including data protection and privacy, shall be governed exclusively by the laws of India.`,
          `Users accessing the Platform from outside India do so at their own risk and are responsible for compliance with local laws, to the extent applicable, without imposing any obligation, liability, or compliance burden on JuriNex under any foreign law.`,
        ],
      },
      {
        heading: "5. USER OBLIGATIONS AND ACCEPTABLE USE",
        paragraphs: [`You represent and warrant that:`],
        bullets: [
          `You are at least 18 years of age.`,
          `You have legal capacity to enter into a binding contract.`,
          `You are accessing the Platform for lawful and professional purposes.`,
          `If using on behalf of an organization, you have authority to bind such entity.`,
          `Not misrepresent Platform outputs as legal advice or court-certified material.`,
          `Not upload content that violates confidentiality, privilege, intellectual property, or third-party rights.`,
          `Not attempt to reverse engineer, scrape, interfere with, or misuse the Platform or its systems.`,
        ],
        extraParagraphs: [
          `The Platform is intended primarily for advocates, lawyers, law firms, corporate legal departments, and legal professionals.`,
          `JuriNex reserves the right to suspend or terminate access for any misuse or violation of these Terms.`,
        ],
      },
      {
        heading: "6. INTELLECTUAL PROPERTY RIGHTS",
        paragraphs: [
          `All intellectual property rights in the Platform, including software, algorithms, models, prompts, content, trademarks, and documentation, vest exclusively with JuriNex.`,
          `No rights are transferred to users except a limited, revocable, non-exclusive, non-transferable license to access and use the Platform in accordance with these terms.`,
        ],
      },
      {
        heading: "7. AI LIMITATIONS AND ACCURACY DISCLAIMER",
        paragraphs: [
          `The Platform utilises automated and artificial intelligence-based systems that generate outputs based on probabilistic models and user-provided inputs.`,
          `Such outputs sometimes may be incomplete, inaccurate, outdated, or contextually inappropriate.`,
          `JuriNex makes no representations or warranties regarding the accuracy, completeness, reliability, or court-admissibility of any output and does not verify case law, statutory amendments, factual accuracy, or jurisdictional applicability.`,
        ],
      },
      {
        heading: "8. LIMITATION OF LIABILITY",
        paragraphs: [
          `To the maximum extent permitted by applicable law, JuriNex, its founders, directors, officers, employees, affiliates, and service providers shall not be liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages, including loss of profits, data, reputation, goodwill, or legal standing, arising out of or relating to use of or reliance upon the Platform or its outputs.`,
        ],
      },
      {
        heading: "9. INDEMNITY",
        paragraphs: [
          `Users agree to fully indemnify, defend, and hold harmless JuriNex, its founders, directors, officers, employees, affiliates, and agents from and against any and all claims, demands, actions, proceedings, losses, damages, liabilities, penalties, and expenses (including reasonable legal fees) arising out of or relating to:`,
        ],
        bullets: [
          `(a) use or misuse of the Platform or its outputs;`,
          `(b) representation of Platform outputs as legal advice or court-ready material;`,
          `(c) violation of these Terms or applicable law;`,
          `(d) infringement of any third-party rights.`,
        ],
        extraParagraphs: [`This indemnity shall survive termination or suspension of access to the Platform.`],
      },
      {
        heading: "10. DATA PROTECTION AND PRIVACY",
        paragraphs: [
          `All personal data processing undertaken in connection with use of the Platform shall be governed exclusively by the Digital Personal Data Protection Act, 2023 (DPDP Act), and the JuriNex Privacy Policy.`,
          `No foreign data protection laws shall apply to JuriNex by virtue of a user's location or access.`,
        ],
      },
      {
        heading: "11. SUSPENSION AND TERMINATION",
        paragraphs: [
          `JuriNex may suspend or terminate user access to the Platform at its sole discretion, with or without notice, for violation of these Terms, security reasons, legal compliance, or business necessity.`,
        ],
      },
      {
        heading: "12. AMENDMENTS",
        paragraphs: [
          `JuriNex reserves the right to modify or update these Terms at any time.`,
          `Continued use of the Platform after publication of revised Terms constitutes acceptance of such changes.`,
        ],
      },
      {
        heading: "13. GOVERNING LAW AND JURISDICTION",
        paragraphs: [
          `These Terms shall be governed by and construed in accordance with the laws of India.`,
          `The courts at Mumbai, India shall have exclusive jurisdiction over any dispute, claim, or proceeding arising out of or relating to these Terms or the Platform.`,
        ],
      },
      {
        heading: "14. SEVERABILITY AND SURVIVAL",
        paragraphs: [
          `If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.`,
          `Clauses relating to disclaimers, limitation of liability, indemnity, governing law, and jurisdiction shall survive termination.`,
        ],
      },
      {
        heading: "15. CONTACT INFORMATION",
        paragraphs: [
          `For any queries relating to these Terms, users may contact JuriNex through its officially designated communication channels.`,
        ],
      },
      {
        heading: "DATA PROCESSING AGREEMENT (INTEGRATED)",
        paragraphs: [
          `This Data Processing Agreement forms an integral part of and is incorporated by reference into the Terms and Conditions and Privacy Policy governing access to and use of the JuriNex platform.`,
          `This Agreement governs processing of personal data by JuriNex strictly in accordance with the Digital Personal Data Protection Act, 2023 (DPDP Act) and applies solely within the legal and jurisdictional framework of India.`,
          `For the purposes of this Agreement, the User acts as the Data Fiduciary and JuriNex acts strictly as a Data Processor, processing personal data only on documented instructions and only for provision of Platform services.`,
          `JuriNex may engage sub-processors as necessary for service delivery and shall implement reasonable technical and organisational safeguards.`,
          `JuriNex may notify users of personal data breaches within a reasonable time as required by applicable Indian law and may retain, delete, or anonymise data in accordance with legal obligations and service requirements.`,
          `No physical audits or on-site inspections are permitted unless required by Indian law or a competent authority.`,
          `The User indemnifies JuriNex for unlawful instructions, invalid consent, or breaches of DPDP obligations by the User.`,
        ],
      },
      {
        heading: "REFUND / CANCELLATION POLICY (INTEGRATED)",
        paragraphs: [
          `Once a subscription, license, or service plan is activated, it cannot be cancelled, whether in part or in full.`,
          `Subscription charges paid to JuriNex are non-refundable, including in cases of dissatisfaction, change of requirements, or discontinuation of use.`,
          `Free trials, demos, or pilot access are provided "as is" and do not create entitlement to refunds after purchase of a paid plan.`,
          `Early termination by the user does not entitle the user to refund, credit, or prorated adjustment.`,
          `JuriNex may modify, suspend, or discontinue features or modules without creating refund entitlement.`,
          `Any exceptional refund is solely at JuriNex's written discretion under internal review policies.`,
        ],
      },
    ],
  },
  dpdpa: {
    title: "Privacy Policy",
    companyName: "JuriNex",
    subtitle: null,
    docTitle: "PRIVACY POLICY",
    docSubtitle: "(DPDP Act, India)",
    lastUpdated: "Latest Version",
    sections: [
      {
        heading: "1. INTRODUCTION",
        paragraphs: [
          `This Privacy Policy sets out the manner in which JuriNex collects, processes, stores, uses, discloses, and protects personal data of users accessing or using the JuriNex platform, website, applications, dashboards, and related services (collectively, the "Platform").`,
          `This Policy is framed strictly in accordance with the Digital Personal Data Protection Act, 2023 ("DPDP Act") and shall be governed exclusively by the laws of India.`,
          `No foreign data protection law or regulation shall apply to JuriNex, irrespective of the user's location or place of access.`,
        ],
      },
      {
        heading: "2. SCOPE AND APPLICABILITY",
        paragraphs: [`This Policy applies to all users of the Platform, including visitors, registered users, enterprise users, and trial users.`],
        bullets: [
          `Indian law alone governs all personal data processing by JuriNex.`,
          `No foreign jurisdiction, authority, or regulatory framework shall have applicability or enforceability against JuriNex.`,
        ],
      },
      {
        heading: "3. CATEGORIES OF PERSONAL DATA COLLECTED",
        paragraphs: [`JuriNex may collect and process the following categories of personal data:`],
        bullets: [
          `Basic identification data such as name, email address, professional designation, and contact details.`,
          `Account and authentication data including login credentials and access identifiers.`,
          `Technical and usage data such as IP address, device identifiers, browser type, operating system, logs, and timestamps.`,
          `User-provided content including documents, prompts, queries, text inputs, and uploaded materials.`,
          `Payment-related information strictly to the extent necessary for transaction processing through third-party payment gateways.`,
        ],
        extraParagraphs: [
          `JuriNex does not store financial instrument details and does not intentionally collect sensitive personal data.`,
          `Users are strictly advised against uploading sensitive personal data; any such upload is deemed voluntary and at the user's own risk.`,
        ],
      },
      {
        heading: "4. PURPOSE OF PROCESSING",
        paragraphs: [
          `Personal data is processed strictly for operation, maintenance, and administration of the Platform; user authentication and access control; security and abuse prevention; compliance with Indian law; and enforcement of contractual rights and dispute resolution.`,
          `JuriNex does not process personal data for the purpose of providing legal advice, legal opinions, or assurance of legal outcomes.`,
        ],
      },
      {
        heading: "5. AI PROCESSING AND USER RESPONSIBILITY",
        paragraphs: [
          `The Platform utilises automated and artificial intelligence-based systems to process user inputs solely for generating outputs requested by the user.`,
          `JuriNex does not review, verify, validate, moderate, or independently assess user-provided content.`,
          `Users remain solely responsible for ensuring uploaded content is lawful and does not breach confidentiality, privilege, data protection requirements, or third-party rights.`,
          `JuriNex expressly disclaims all liability arising from user-provided content, including privilege waiver, confidentiality breach, or unlawful processing.`,
        ],
      },
      {
        heading: "6. DATA SHARING AND DISCLOSURE",
        paragraphs: [`JuriNex does not sell or commercially exploit personal data.`],
        bullets: [
          `Disclosure to service providers, infrastructure partners, and vendors under confidentiality obligations.`,
          `Disclosure to payment processors strictly for transaction facilitation.`,
          `Disclosure to governmental, judicial, regulatory, or law enforcement authorities where required by Indian law or legal process.`,
        ],
        extraParagraphs: [`Such disclosure shall not constitute a breach of this Policy.`],
      },
      {
        heading: "7. CROSS-BORDER ACCESS",
        paragraphs: [
          `While the Platform may be accessed globally, all personal data processing decisions, controls, and compliance obligations are determined solely under Indian law.`,
          `Access from outside India does not create foreign jurisdiction or compliance obligations under foreign data protection laws.`,
        ],
      },
      {
        heading: "8. DATA RETENTION",
        paragraphs: [
          `Personal data shall be retained only for 30 days as is reasonably necessary to fulfil the stated purposes, comply with Indian legal requirements, resolve disputes, enforce agreements, or protect legitimate business interests.`,
          `JuriNex may retain anonymised or aggregated data indefinitely.`,
        ],
      },
      {
        heading: "9. DATA SECURITY",
        paragraphs: [
          `JuriNex implements reasonable and industry-appropriate technical and organisational security measures to protect personal data against unauthorised access, alteration, disclosure, loss, or misuse.`,
          `No method of transmission or storage is completely secure, and JuriNex disclaims any guarantee of absolute or uninterrupted security.`,
        ],
      },
      {
        heading: "10. USER RIGHTS",
        paragraphs: [`User rights under this Policy are limited strictly to those provided under the DPDP Act.`],
        bullets: [
          `Compliance with Indian law.`,
          `Ongoing investigations or dispute resolution.`,
          `Enforcement of contractual or legal rights.`,
          `Protection of JuriNex's legitimate interests.`,
        ],
        extraParagraphs: [`Requests for access, correction, or erasure may be refused or restricted where required by the above conditions.`],
      },
      {
        heading: "11. THIRD-PARTY SERVICES",
        paragraphs: [
          `The Platform may contain links to third-party websites or services.`,
          `JuriNex exercises no control over such third parties and is not responsible for their privacy practices, content, or security.`,
          `Access to third-party services is at the user's own risk.`,
        ],
      },
      {
        heading: "12. AMENDMENTS",
        paragraphs: [
          `JuriNex reserves the absolute right to amend, modify, or update this Privacy Policy at any time.`,
          `Continued use of the Platform following publication of changes constitutes deemed acceptance of the revised Policy.`,
        ],
      },
      {
        heading: "13. GOVERNING LAW AND JURISDICTION",
        paragraphs: [
          `This Privacy Policy shall be governed by and construed exclusively in accordance with the laws of India.`,
          `The courts at Mumbai, India shall have exclusive jurisdiction over any dispute arising out of or relating to this Policy.`,
        ],
      },
      {
        heading: "14. CONTACT INFORMATION",
        paragraphs: [
          `For any questions or concerns relating to this Privacy Policy or personal data processing, users may contact JuriNex through its officially designated communication channels.`,
        ],
      },
    ],
  },
}

const PolicyBody = ({ policy }) => (
  <div className="space-y-5">
    <div className="pb-4 border-b border-juri-line">
      <h3 className="font-playfair text-xl font-bold text-juri-ink">{policy.companyName}</h3>
      {policy.subtitle && <p className="mt-0.5 font-dmSans text-sm font-semibold text-juri-ink">{policy.subtitle}</p>}
      <p className="mt-2 font-dmSans text-sm font-bold text-juri-ink">{policy.docTitle}</p>
      {policy.docSubtitle && <p className="font-dmSans text-sm text-juri-muted">{policy.docSubtitle}</p>}
      <p className="mt-1 font-dmSans text-sm text-juri-muted">
        <span className="font-semibold text-juri-ink">Last Updated:</span> {policy.lastUpdated}
      </p>
    </div>

    {policy.sections.map((sec) => (
      <div key={sec.heading} className="space-y-2">
        <p className="font-dmSans text-sm font-bold text-juri-ink">{sec.heading}</p>

        {sec.subSections?.map((sub) => (
          <div key={sub.subHeading} className="space-y-1.5 pl-1">
            <p className="font-dmSans text-sm font-semibold text-juri-ink">{sub.subHeading}</p>
            {sub.paragraphs?.filter(Boolean).map((p, i) => (
              <p key={i} className="font-dmSans text-sm leading-relaxed text-juri-muted">{p}</p>
            ))}
            {sub.important && (
              <p className="font-dmSans text-sm font-semibold leading-relaxed" style={{ color: "#E0334A" }}>
                {sub.important}
              </p>
            )}
            {sub.extraParagraphs?.map((p, i) => (
              <p key={i} className="font-dmSans text-sm leading-relaxed text-juri-muted">{p}</p>
            ))}
            {sub.infoLines?.map(({ label, value }) => (
              <p key={label} className="font-dmSans text-sm text-juri-muted">
                <span className="font-semibold text-juri-ink">{label}</span> {value}
              </p>
            ))}
          </div>
        ))}

        {sec.paragraphs?.map((p, i) => (
          <p key={i} className="font-dmSans text-sm leading-relaxed text-juri-muted">{p}</p>
        ))}

        {sec.important && (
          <p className="font-dmSans text-sm font-semibold leading-relaxed" style={{ color: "#E0334A" }}>
            {sec.important}
          </p>
        )}

        {sec.bullets?.map((b) => (
          <div key={b} className="flex items-start gap-2 pl-1">
            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-juri-muted" />
            <p className="font-dmSans text-sm leading-relaxed text-juri-muted">{b}</p>
          </div>
        ))}
      </div>
    ))}
  </div>
)

/**
 * Props:
 *   policyKey  — "terms" | "dpdpa"
 *   onClose    — called on X or backdrop click
 *   onAccept   — called on "Accept & Close" (optional — omit for view-only mode)
 */
const PolicyModal = ({ policyKey, onClose, onAccept }) => {
  const policy = POLICIES[policyKey]
  const bodyRef = useRef(null)
  const [hasReachedBottom, setHasReachedBottom] = useState(false)

  useEffect(() => {
    const bodyEl = bodyRef.current
    if (!bodyEl) return

    const checkScrollEnd = () => {
      const isAtBottom = bodyEl.scrollTop + bodyEl.clientHeight >= bodyEl.scrollHeight - 2
      setHasReachedBottom(isAtBottom)
    }

    // Reset gate for each policy open, but auto-pass if no scroll is needed.
    setHasReachedBottom(false)
    checkScrollEnd()
  }, [policyKey])

  if (!policy) return null

  return (
    <>
      <Motion.div
        className="fixed inset-0 z-50 bg-black/40"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
        onClick={onClose}
      />
      <div className="fixed inset-0 z-50 flex items-center justify-center px-4 py-8 pointer-events-none">
        <Motion.div
          className="pointer-events-auto relative flex w-full max-w-xl flex-col rounded-2xl bg-white shadow-2xl overflow-hidden"
          style={{ maxHeight: "85vh" }}
          initial={{ opacity: 0, y: 40, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1, transition: { type: "spring", stiffness: 340, damping: 28 } }}
          exit={{ opacity: 0, y: 20, scale: 0.97 }}
        >
          {/* Header */}
          <div className="flex shrink-0 items-center justify-between border-b border-juri-line px-6 py-4">
            <h2 className="font-playfair text-lg font-bold text-juri-ink">{policy.title}</h2>
            <button
              type="button"
              onClick={onClose}
              className="rounded-full p-1.5 text-gray-400 transition hover:bg-gray-100 hover:text-gray-700"
            >
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Scrollable body */}
          <div
            ref={bodyRef}
            onScroll={() => {
              const bodyEl = bodyRef.current
              if (!bodyEl) return
              const isAtBottom = bodyEl.scrollTop + bodyEl.clientHeight >= bodyEl.scrollHeight - 2
              if (isAtBottom) setHasReachedBottom(true)
            }}
            className="flex-1 overflow-y-auto px-6 py-5"
          >
            <PolicyBody policy={policy} />
          </div>

          {/* Footer */}
          <div className="shrink-0 border-t border-juri-line px-6 py-4 flex justify-end">
            {hasReachedBottom ? (
              <Motion.button
                type="button"
                onClick={onAccept ?? onClose}
                className="rounded-xl px-8 py-2.5 font-dmSans text-sm font-bold text-white shadow-md"
                style={{ backgroundColor: "#E0334A" }}
                whileHover={{ scale: 1.02, boxShadow: "0 6px 20px rgba(224,51,74,0.4)" }}
                whileTap={{ scale: 0.97 }}
              >
                {onAccept ? "Accept & Close" : "Close"}
              </Motion.button>
            ) : (
              <p className="font-dmSans text-sm text-juri-muted">
                Scroll to the bottom to continue.
              </p>
            )}
          </div>
        </Motion.div>
      </div>
    </>
  )
}

export default PolicyModal
